# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/dsmith/Desktop/transmission_test_split/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/dsmith/Desktop/transmission_test_split/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:kc705:part0:1.3 [current_project]
add_files -quiet /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/clk_gen/clk_gen.dcp
set_property used_in_implementation false [get_files /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/clk_gen/clk_gen.dcp]
add_files -quiet /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/ila_0/ila_0.dcp
set_property used_in_implementation false [get_files /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/ila_0/ila_0.dcp]
add_files -quiet /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/clk_gen_1/clk_gen_1.dcp
set_property used_in_implementation false [get_files /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/clk_gen_1/clk_gen_1.dcp]
add_files -quiet /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/ila_1/ila_1.dcp
set_property used_in_implementation false [get_files /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/ila_1/ila_1.dcp]
add_files -quiet /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/ila_2/ila_2.dcp
set_property used_in_implementation false [get_files /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/ila_2/ila_2.dcp]
add_files -quiet /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/ila_3/ila_3.dcp
set_property used_in_implementation false [get_files /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/ila_3/ila_3.dcp]
add_files -quiet /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.dcp
set_property used_in_implementation false [get_files /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.dcp]
read_verilog -library xil_defaultlib {
  /home/dsmith/Desktop/transmission_test_split/files/scrambler.v
  /home/dsmith/Desktop/transmission_test_split/files/descrambler.v
}
read_vhdl -library xil_defaultlib {
  /home/dsmith/Desktop/transmission_test_split/files/delay_controller_wrap.vhd
  /home/dsmith/Desktop/transmission_test_split/files/serdes_1_to_468_idelay_ddr.vhd
  /home/dsmith/Desktop/transmission_test_split/files/serdes8to1.vhd
  /home/dsmith/Desktop/transmission_test_split/files/serdes32to8.vhd
  /home/dsmith/Desktop/transmission_test_split/files/gearbox66to32.vhd
  /home/dsmith/Desktop/transmission_test_split/files/gearbox32to66.vhd
  /home/dsmith/Desktop/transmission_test_split/files/loopback128gbps2.vhd
  /home/dsmith/Desktop/transmission_test_split/files/comparator.vhd
  /home/dsmith/Desktop/transmission_test_split/files/generator.vhd
  /home/dsmith/Desktop/transmission_test_split/files/aurora_tx_lane128.vhd
  /home/dsmith/Desktop/transmission_test_split/files/aurora_rx_lane.vhd
  /home/dsmith/Desktop/transmission_test_split/files/loopback128gbps.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/constrs_1/new/testing.xdc
set_property used_in_implementation false [get_files /home/dsmith/Desktop/transmission_test_split/project_1/project_1.srcs/constrs_1/new/testing.xdc]


synth_design -top loopback128gbps -part xc7k325tffg900-2


write_checkpoint -force -noxdef loopback128gbps.dcp

catch { report_utilization -file loopback128gbps_utilization_synth.rpt -pb loopback128gbps_utilization_synth.pb }
