# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dsmith/Desktop/transmission_test/project_1/project_1.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.xci
# IP: The module: 'clk_wiz_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dsmith/Desktop/transmission_test/project_1/project_1.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dsmith/Desktop/transmission_test/project_1/project_1.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dsmith/Desktop/transmission_test/project_1/project_1.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/dsmith/Desktop/transmission_test/project_1/project_1.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.xci
# IP: The module: 'clk_wiz_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dsmith/Desktop/transmission_test/project_1/project_1.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dsmith/Desktop/transmission_test/project_1/project_1.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dsmith/Desktop/transmission_test/project_1/project_1.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
